version: "3"
services:

  python:
    container_name: activity_model_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    volumes:
      - ./requirements.txt:/application/requirements.txt
      - ./activity_model_backend/:/application/activity_model_backend/
    links:
      - mysql
    ports:
      - "8001:8001"
    restart: always

  mysql:
   container_name: activitymodeldb
   image: mysql:5.6
   ports:
     - "3308:3306"
   environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: activitymodel
      MYSQL_DATABASE: activitymodel
      MYSQL_USER: activitymodel
      MYSQL_PASSWORD: activitymodel

volumes:
  esdata01:
    driver : local


    